### ISSUE TITLE
💡 Change color scheme of the application

### ISSUE THREAD

**Issue by pyuxiang** [AY2021S2-CS2103-W16-3/tp#100]
### Describe the issue
*What is the problem, if any? What is the desired behavior?*

The dark theme is by default. Perhaps change the color theme to something else to personalize our application.

________________________________________________________________
### Additional context
*Describe possible and/or alternative solutions, to highlight required scope of work.*

As simple as modifying `darkTheme.css` under Resources to change the colors.

**Comment by zhengruoxin** [comment]
Some ideas (screenshots from online): 
![photo_2021-03-14 16 35 14](https://user-images.githubusercontent.com/65821483/111062412-87758280-84e3-11eb-8c95-2a319a141f4f.jpeg)
![photo_2021-03-14 16 35 16](https://user-images.githubusercontent.com/65821483/111062415-8a707300-84e3-11eb-865a-e57c4abb426b.jpeg)
![photo_2021-03-14 16 35 18](https://user-images.githubusercontent.com/65821483/111062417-8c3a3680-84e3-11eb-8e65-e5d455b2fb07.jpeg)

**Comment by garyljj** [comment]
Alternatively, idea to put the logo as a background. Altho tbh I dont have much idea how to do it haha
