### ISSUE TITLE
💡 Add details of command being undone for UndoCommand

### ISSUE THREAD

**Issue by nickyfoo** [AY2021S2-CS2103-W16-3/tp#108]
### Describe the issue
Currently the feedback given to the user is "Undo Completed!", which is not very informative.

It might be better to add the specific command that is being undone, e.g. "Undid delete 8"

**Comment by pyuxiang** [comment]
Got confused a little: Isn't the undo command feature part of your PR, and not yet integrated into the master branch? Can raise this issue in the PR first, then open an issue from there if not implemented.

**Comment by nickyfoo** [comment]
Ah that's true, will do that instead.

**Comment by pyuxiang** [comment]
Reopening this, issue still persists from https://github.com/AY2021S2-CS2103-W16-3/tp/pull/107.
