### ISSUE TITLE
🐞 Calling `tags` command when no tags are present raises error

### ISSUE THREAD

**Issue by pyuxiang** [AY2021S2-CS2103-W16-3/tp#109]
### Describe the issue
*What is expected to happen? How can it be reproduced?*

Application raises `java.lang.StringIndexOutOfBoundsException` when no tags are present in the person list, and `tags` is called.

Reproduction steps:
1. `clear` (removes all tags)
2. `tags` (or any variant thereof)

________________________________________________________________
### Additional context
*Suggest possible bug sources (or [reference them](https://docs.github.com/en/github/managing-your-work-on-github/opening-an-issue-from-code)). Add screenshots if applicable.*

![image](https://user-images.githubusercontent.com/28663438/111124452-8019ac00-85ab-11eb-99f7-5bfce1f20bd1.png)

Likely a missing empty collection check in `TagsCommand`.

________________________________________________________________
### Environment
 - OS: Windows 10
 - JDK version: 11

**Comment by nickyfoo** [comment]
The same exception is thrown when `tags -f [CHAR]` is called, where CHAR is any character not in any tags, e.g. 
`tags -f z` for the sample data.

**Comment by pyuxiang** [comment]
`tags` command deprecated with #192.
