### ISSUE TITLE
💡 Limit on history states

### ISSUE THREAD

**Issue by garyljj** [AY2021S2-CS2103-W16-3/tp#112]
### Describe the issue
*What is the problem, if any? What is the desired behavior?*
Suggestion to add a max limit on history states. In case we are worried about memory problems.
Can be edited when implementing redo.

______________________________________________________________
### Additional context
*Describe possible and/or alternative solutions, to highlight required scope of work.*

**Comment by pyuxiang** [comment]
Did we conclude whether we wanted to do this, the other time we had a discussion?

**Comment by garyljj** [comment]
I think we agreed that memory not really a concern atm since undo history doesnt carry over across sessions.
But i think no harm adding later on!

**Comment by pyuxiang** [comment]
> I think we agreed that memory not really a concern atm since undo history doesnt carry over across sessions.

Floating an idea, what about (1) setting undo history to a cap higher than the average number of commands used in a single session, and (2) letting undo history carry over sessions? It's a little like vim's swap files.

Validation of the swap history can be achieved by storing the latest address book state in a lightweight hashed format, so it avoids users abusing the swap file to trigger invalid undos.

**Comment by garyljj** [comment]
Yea I dont mind. I feel like even ~10-15 undo is probably more than enough.
But i think wait til event branch is integrated with the history too

**Comment by nickyfoo** [comment]
As discussed before, since the StateHistory is refreshed on each running of the application and does not carry over between sessions, it is unlikely that it will cause a memory problem, and so it will not be implemented for this milestone.
