### ISSUE TITLE
📖 As a Clumsy User, I can undo/redo a wrongly input command

### ISSUE THREAD

**Issue by Ellevy** [AY2021S2-CS2103-W16-3/tp#134]
...so that I can fix mistakes.

________________________________________________________________
### Describe the feature
*Define precisely the desired behavior.*
When the user accidentally types in a wrong command, they can choose to undo or redo.

________________________________________________________________
### Additional context
*What is the current implementation, and the required scope of work?*
Current implementation only allows undo for people. Need to add for events too.

**Comment by pyuxiang** [comment]
Seconding this, @nickyfoo. This is a pretty urgent feature, for undoing changes to events.

Redo is a secondary feature, since there is already a command history.
