### ISSUE TITLE
📖 As Welfare IC, I can set a date for a birthday plan (event)

### ISSUE THREAD

**Issue by Ellevy** [AY2021S2-CS2103-W16-3/tp#139]
...so that I can ensure details are planned on time.

________________________________________________________________
### Describe the feature
*Define precisely the desired behavior.*

________________________________________________________________
### Additional context
*What is the current implementation, and the required scope of work?*
Currently the date in event is Birthday. Should come up with a Date then let person's Birthday inherit from Date.

**Comment by pyuxiang** [comment]
Already fixed in #145, in previous milestone.
