### ISSUE TITLE
💡 Help/F1 button should provide help same way as `help` command

### ISSUE THREAD

**Issue by Ellevy** [AY2021S2-CS2103-W16-3/tp#144]
### Describe the issue
*What is the problem, if any? What is the desired behavior?*

Currently, clicking the Help button or F1 button causes a popup window with the link to the user guide.

![image](https://user-images.githubusercontent.com/46534252/111898044-75a15b80-8a5e-11eb-8581-19bb80aee0a0.png)

Would be good to change it and standardise the behaviour with the `help` command

________________________________________________________________
### Additional context
*Describe possible and/or alternative solutions, to highlight required scope of work.*

**Comment by pyuxiang** [comment]
I agree, though I also think the UserGuide is a good starting point for the users. Perhaps we can consider link drop in the result pane when `help` command is called.

On the same note, I think a nice feature would be to remove the menubar feature. Takes up much needed real estate only 😜

**Comment by nickyfoo** [comment]
Yup, I think it'll be good to have the `help` command provide both immediate (summarised) help, and a reference to the link at the bottom for users to explore the nuances
