### ISSUE TITLE
🐞  List allows both any and exact flag

### ISSUE THREAD

**Issue by garyljj** [AY2021S2-CS2103-W16-3/tp#162]
### Describe the issue
*What is expected to happen? How can it be reproduced?*
`list --any --exact -n hi`

Since `list` by default is `--any`, it simply checks for the existence of `--exact`
Thus, if both appears -> means `--exact` exist -> does `--exact` search -> doesnt throw error

Solution:
1. Check if both exist and throw error
2. Remove `--any` flag. So, by default is "any", if given flag, do "exact".
    * So that this case will never occur

`delete -t` also have the same issue. I will update it to follow the solution chosen by `list`
`elist` too for @Ellevy to update

________________________________________________________________
### Additional context
*Suggest possible bug sources (or [reference them](https://docs.github.com/en/github/managing-your-work-on-github/opening-an-issue-from-code)). Add screenshots if applicable.*

________________________________________________________________
### Environment
 - OS: [ macOS (Big Sur) / Windows 10 / Linux (OpenSUSE) ]
 - JDK version: 11

**Comment by garyljj** [comment]
not a bug

**Comment by pyuxiang** [comment]
`--any` is not the opposite of `--exact` functionality
