### ISSUE TITLE
💡 Clearer description of undo/redo

### ISSUE THREAD

**Issue by garyljj** [AY2021S2-CS2103-W16-3/tp#222]
### Describe the issue
*What is the problem, if any? What is the desired behavior?*
To avoid any misconception, emphasis in UG that undo/redo ONLY reverts when there are changes to list (eg. `add`, `edit` etc).
And does not save state for searches/ sorts (eg. `list`)

**Comment by pyuxiang** [comment]
Color me surprised, someone did raise this as a bug #239...
