### ISSUE TITLE
🐞 Possible integer overflow error

### ISSUE THREAD

**Issue by pyuxiang** [AY2021S2-CS2103-W16-3/tp#285]
### Describe the issue
*What is expected to happen? How can it be reproduced?*

To check if this error is present in our repository, fix if needed.
See the [original bug report](https://github.com/AY2021S2-CS2103T-T12-4/tp/issues/485) from another project for context. Said to arise from previous `AddressBook3` implementation.

________________________________________________________________
### Additional context
*Suggest possible bug sources (or [reference them](https://docs.github.com/en/github/managing-your-work-on-github/opening-an-issue-from-code)). Add screenshots if applicable.*

`ParserUtil.java`

________________________________________________________________
### Environment
 - OS: -
 - JDK version: 11

**Comment by garyljj** [comment]
For this, i think the easiest fix is to just update the UG that a max value for `INDEX` is 2147483647
