### ISSUE TITLE
🐞 Address Book default font does not work on certain Mac OS versions

### ISSUE THREAD

**Issue by glennljs** [AY2021S2-CS2103-W16-3/tp#71]
<img width="776" alt="Screenshot of Address Book" src="https://user-images.githubusercontent.com/43852051/110231031-27fdfc80-7f50-11eb-9614-9dee25e2d816.png">

Solution probably to store and distribute the font as part of the app's resources so it will definitely work on all systems.

**Comment by pyuxiang** [comment]
Courtesy of @glennljs: Issue only happens when `gradle run` command is used. If built normally and open the jar, it works fine. Perhaps grade adds the font as a separate resource internally.

**Comment by pyuxiang** [comment]
If not fixing, can assign `tag::wontfix`, remove the `priority` label, and close the issue.
