### ISSUE TITLE
💡 Resize GUI textbox to fit messages

### ISSUE THREAD

**Issue by garyljj** [AY2021S2-CS2103-W16-3/tp#76]
### Describe the issue
*What is the problem, if any? What is the desired behavior?*
Textbox in HippoCampus GUI currently too small to fit help messages.
It is currently scrollable, but preferably resized to show more.
Or at least allow it to be resized with window.

________________________________________________________________
### Additional context
*Describe possible and/or alternative solutions, to highlight required scope of work.*

**Comment by pyuxiang** [comment]
Probably here, where the dimensions for the result display are specified:

https://github.com/AY2021S2-CS2103-W16-3/tp/blob/1d205c019aa61650b61f437bc8d77a82bfa0b5c2/src/main/resources/view/MainWindow.fxml#L42-L47

Overall window size seems to be specified here:

https://github.com/AY2021S2-CS2103-W16-3/tp/blob/1d205c019aa61650b61f437bc8d77a82bfa0b5c2/src/main/java/seedu/address/commons/core/GuiSettings.java#L11-L14
