### ISSUE TITLE
💡 Input history

### ISSUE THREAD

**Issue by garyljj** [AY2021S2-CS2103-W16-3/tp#87]
### Describe the issue
*What is the problem, if any? What is the desired behavior?*
Cycle through input history with up/down button.
Easier for user to retype command if small typo/ if want to type a similar command.
Also easier for us to test.
________________________________________________________________
### Additional context
*Describe possible and/or alternative solutions, to highlight required scope of work.*

**Comment by pyuxiang** [comment]
Any suggestions to implement this? Thinking of an `InputHistory` class native to the parser / executor class. Probably also need to register event handlers for up/down arrow keys in the input field box, see this [SO post](https://stackoverflow.com/a/36371310) for a possible implementation guide.

**Comment by garyljj** [comment]
I implemented a similar feature in my IP so I can probably PR later and see if yall like it
