### ISSUE TITLE
💡 Deletion of non-existent tag should reflect as an error instead of success

### ISSUE THREAD

**Issue by pyuxiang** [AY2021S2-CS2103-W16-3/tp#89]
### Describe the issue
*What is the problem, if any? What is the desired behavior?*

Upon attempt to delete a non-existent tag (e.g. in the case of typos), the application reflects a success state. Ought to indicate that none of such tags were found instead, to feedback a potential user input error to the user.

________________________________________________________________
### Additional context
*Describe possible and/or alternative solutions, to highlight required scope of work.*

![image](https://user-images.githubusercontent.com/28663438/110581702-f8e0c880-81a5-11eb-9b9c-94eda89cedb4.png)

Contrast this with the behaviour when deleting by indices:

![image](https://user-images.githubusercontent.com/28663438/110581828-37768300-81a6-11eb-9968-f7ca6f0a9006.png)

Requires modification of `DeleteTagCommand`.

**Comment by garyljj** [comment]
Yup I considered this but thought it was too inefficient to scan through all whole list to see if all tags specified exists.

Perhaps I can add some kind of static set in Tags to keep track of all tags that currently exists
